[theme]
theme = "native"

#[[block]]
#block = "disk_space"
#info_type = "available"
#alert_unit = "GB"
#warning = 20.0
#alert = 10.0
#format = "DSK: $available / $total"

#[[block]]
#block = "memory"
#format = "MEM: $mem_total_used_percents"
#format_alt = "SWP: $swap_used_percents"

#[[block]]
#block = "cpu"
#interval = 1

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "net"
format = " $ssid"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%R')"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
