[theme]
theme = "native"

[[block]]
block = "custom"
command = "nmcli -t -f NAME,TYPE connection show --active | awk -F: '$2==\"vpn\"{print $1; exit}'"
interval = 3
hide_when_empty = true
json = false
format = " {$text}"    # иконка замка (Nerd Font)
# on_click = "nmcli connection down id $(nmcli -t -f NAME,TYPE connection show --active | awk -F: '$2==\"vpn\"{print $1; exit}')"  # опционально

[[block]]
block = "net"
device = "wlp59s0"
format = "  $ssid"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%R')"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
