[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 11.0

[font.bold]
family = "Monocode"
style = "Medium"

[font.normal]
family = "Monocode"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 3

[selection]
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>'''

[window]
decorations = "None"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = false

[keyboard]
