[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 14.0

[font.bold]
family = "Consolas"
style = "Regular"

[font.normal]
family = "Consolas"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 100
multiplier = 3

[selection]
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>'''

[window]
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 35

[colors]
draw_bold_text_with_bright_colors = false

[keyboard]
